### PR TITLE
Update Product Name to be user-friendlier

### PR DESCRIPTION
**Pull request by designatednerd**
A stab at doing #136 a bit simpler.

Before: 
IMG_1767

After: 
Simulator Screen Shot - iPhone Xʀ - 2019-04-15 at 16 16 54

### CODE REVIEW

**Comment by designatednerd** [comment]
Note: The `-` is there instead of a space because Xcode freaks the hell out if you have a space in your `Product Name`. Probably worth eventually investigating what key Auth0 is using to pull this (they should *probably* be using the bundle display name and not the Product name), but might be overkill since the prod version is just "Oya".

**Comment by prasanthu** [comment]
@oisinzimmermann do you think "Oya-development" is enough ?

**Comment by designatednerd** [comment]
Note that prod version will just by "Oya"

**Comment by prasanthu** [comment]
@designatednerd The way I did it allows space ;-)

**Comment by designatednerd** [comment]
I mean, fair, but I feel like if we don't absolutely need that it's not worth the additional hassle

**Comment by prasanthu** [comment]
@designatednerd I think you have to change Pod names now. If you can't avoid that, it wil most like be very similar to https://github.com/ostelco/ostelco-ios-client/pull/136.

**Comment by prasanthu** [comment]
> @designatednerd I think you have to change Pod names now. If you can't avoid that, it will most like be very similar to #136.

I thought the build failed. May be I clicked the wrong link for circle CI

**Comment by designatednerd** [comment]
@prasanthu With this method you should not have to change the pod names because the names of the targets themselves have not changed. That's a huge part of why this is WAY fewer changes.

**Pull request merged**
